name: Linting on Pull Request

on:
  pull_request:
    types: [opened,synchronize]

jobs:
  lint: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get changed files
      run: |
        git status
        git diff origin/main
